# Autogenerated by devscripts/update-version.py

__version__ = '2024.07.10'

RELEASE_GIT_HEAD = '7ead7332af69422cee931aec3faa277288e9e212'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2024.07.10'
